name: sangfor_plugin
description: A new flutter plugin project.
version: 1.0.2
homepage: https://github.com/firesera2930/sangfor_plugin

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  
flutter:
  plugin:
    platforms:
      android:
        package: com.firesera.sangfor_plugin
        pluginClass: SangforPlugin
      ios:
        pluginClass: SangforPlugin
